#! /bin/tcsh

#setup for multi-basis adaptive DNN training




set ALLARGS=($*)

if ( $#argv != 4 ) then
    echo "Usage: $0 BLE src-MLP-ABS_PATH srcMLP tgtdir"
    exit 1
endif

set BLE=$1
set MLPSRC=$2
set MLPDIR=$3
set TGT=$4

source $BLE

set BASE=$CONVERTDIR
set BASETOOLSDIR=${BASE}/base

set TSET=traincv



set FTGT=$TGT
set TRAINSET=step-mbt-nobias-lamtune
if (! -d CMDs/$FTGT) mkdir -p CMDs/$FTGT
echo "------------------------------------" >> CMDs/$FTGT/${TRAINSET}.cmds
echo "$0 $ALLARGS" >> CMDs/${FTGT}/${TRAINSET}.cmds
echo "------------------------------------" >> CMDs/$FTGT/${TRAINSET}.cmds




if ( -d $TGT ) then
    echo "Directory $TGT exists - delete to rerun"
    exit 1
else
    mkdir -p $TGT
endif

cd ${TGT}

ln -s ${BASETOOLSDIR} base

mkdir -p lib/mbt/
ln -s ${MLPSRC}/lib/mbt/${TSET}.segmap lib/mbt/
ln -s ${MLPSRC}/lib/mbt/${TSET}.lam lib/mbt/${TSET}.lam.init

ln -s ${MLPSRC}/lib/* lib/

mkdir -p data
ln -s ${MLPSRC}/data/pfile data/

ln -s ${MLPSRC}/${MLPDIR} fwdMLP

mkdir htefiles
cp base/htefiles/HTE.mlp_cdstate htefiles

